### ISSUE TITLE
Allow Zone Configuration

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-i18n#1]
```yaml
i18n:

    # set mode (~|language|country)
    mode: country

    # define a country adapter (flat|coreshop|custom)
    country_adapter: i18n.country.adapter.flat

    # static route translations
    translations:
        -   url-news:
                de: 'news'
                en: 'neuigkeiten'
                it: 'notizia'
                fr: 'nouveaute'

    # zones are optional
    # if no zones are defined the global configuration applies to all pages
    zones:

        # example 1: complex country / language i81n
        -   id: 1
            name: 'zone 1'
            # domains must be the main domain of page
            domains: ['your-page.eu', 'your-page.cz', 'your-page.de', 'your-page.pl']
            config:
                mode: country
                country_adapter: i18n.country.adapter.coreshop
                translations: ~

        # example 2: only language based i18n
        -   id: 2
            name: 'zone 2'
            domains: ['special-page.com', 'other-domain.jp']
            config:
                mode: language
                country_adapter: ~
                translations: ~
        # example 3: No i18n since the webpage is just a simple page
        -   id: 3
            name: 'zone 3'
            domains: ['boring-page.com']
            config:
                mode: ~
                country_adapter: ~
                translations: ~
```
