### ISSUE TITLE
Allow parameters for translation config 

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-i18n#115]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Allow yaml parameters for i18n.translations and i18n.zones.zonexy.config.translations.

Example yaml config:
```
parameters:
    i18n_translations:
        -   key: 'event'
            values:
                de: 'veranstaltung'
                fr: 'evenement'
                en: 'event'

i18n:
    translations: '%i18n_translations%'
    zones:
        zonexy:
            config:
                translations: '%i18n_translations%'
```

Current Exception:
`Invalid type for path "i18n.translations". Expected "array", but got "string"`
