### ISSUE TITLE
nofollow tags

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-i18n#5]
In documents, we're able to add meta elements like this:

```html
 <meta name="robots" content="nofollow" />
```
Should we implement a setting node to define no follow tags to static routes or even symfony routes?

```yaml
i18n:
    meta:
        nofollow:
            - 'static_route_name'
            - 'symfony_route_name'
```
