### ISSUE TITLE
Zones based on language documents

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [dachcom-digital/pimcore-i18n#54]
Assume you have only 1 domain and a document structure like /example.org/de/123 and /example.org/en/123. As zones are currently based on domains of sites how is it possible to get a language switch which contains DE and EN? Currently I only can create zone for domain example.org and so the `getActiveLanguages()` only gets the 1 language - the one which is set for /example.org site.

**Comment by solverat** [comment]
Hey @BlackbitNeueMedien. In fact, you don't need to configure zones. They are only required if you're using multiple sites which are connected.

In your case, this should be enough:

```yaml
i18n:
    mode: language
    locale_adapter: system
```

**Comment by BlackbitNeueMedien** [comment]
In fact I have multiple sites. Without any further zone configuration `getActiveLanguages()` delivered 3 times "DE".
The whole document structure looks like this:
domain.de
-- ...
example.org
-- de
---- 123
-- en
---- 123
other-domain.com
-- ...

I linked de and en as well as de/123 and en/123 with the localization tool. 
When I call example.org/de I want `getActiveLanguages()` to return example.org/de (as active language) and example.org/en - but not other-domain.com nor domain.de.

**Comment by solverat** [comment]
Perfekt. 

## Pre-Config
Be sure that the site document `example.org` has **no defined language** (Document => "Navigation & Settings" => "Language" Dropdown: Select empty and save)

## Configuration Example:

```yaml
i18n:
    mode: language
    locale_adapter: system
    registry:
        redirector:
            cookie:
                enabled: false
    zones:
        zone1:
            id: 1
            name: 'domain_de'
            domains:
                - 'domain.de'
            config:
                mode: language
                locale_adapter: system
                translations: ~
        zone2:
            id: 2
            name: 'example_org'
            domains:
                - 'example.org'
            config:
                mode: language
                locale_adapter: system
                translations: ~
        zone3:
            id: 3
            name: 'other_domain_com'
            domains:
                - 'other-domain.com'
            config:
                mode: language
                locale_adapter: system
                translations: ~
```

## View

```twig
<div class="languages">
    <ul>
        {% for language in i18n_context('getActiveLanguages') %}
            <li><a href="{{ language.linkedHref }}">{{ language.iso }}</a></li>
        {% endfor %}
    </ul>
</div>
```
```
