### ISSUE TITLE
No redirect with Safari browser

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [dachcom-digital/pimcore-i18n#62]
I have a site document with the domain `www.staging.example.org` and the following configuration in ma `app/config/config.yml`:
```yml
i18n:
    zones:
        zone_blackbit:
            id: 1
            # domains must be the main domain of page
            domains: 
                - "www.staging.example.org"
            config:
                mode: language
                locale_adapter: system
                translations: ~
```
(Actually I have some more zones for the other site documents but I think this does not matter here)

The site document `www.staging.example.org` has no set language. Below this document there are documents `en` and `de` with the correct languages set.
When I access https://www.staging.example.org in Firefox or Chrome I get redirected to https://www.staging.example.org/de (or /en depending on `Accept-Language` header) but in Safari I do not get redirected but stay on https://www.staging.example.org. Can you think of a cause for that?
