### ISSUE TITLE
Use Attributes as Keys in Zone Configuration

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-i18n#9]
Currently zones are configured as simple arrays:

```yaml
zones:
        -
            id: 1
            name: 'zone 1'
            domains:
        -
            id: 2
            name: 'zone 2'
            domains:
```

when using multiple environments the subconfig gets append instead of merged. Change it to key values:
 
```yaml
zones:
       zone1:
            id: 1
            name: 'zone 1'
            domains:
       zone2:
            id: 2
            name: 'zone 2'
            domains:
```
